// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

public class RegistrarInspectorYEstablecimientoTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
    
    System.setProperty("webdriver.chrome.driver", "/chromedriver");
    driver = new ChromeDriver();
  }
  
  @After
  public void tearDown() {
    driver.quit();
  }
  
  @Test
  public void registrarinspectoryestablecimiento() {
    driver.get("http://localhost:8080/iNspector/");
    driver.manage().window().setSize(new Dimension(1552, 840));
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).sendKeys("root");
    driver.findElement(By.name("password")).sendKeys("root");
    driver.findElement(By.cssSelector(".btn:nth-child(3)")).click();
    driver.findElement(By.name("nombre")).click();
    driver.findElement(By.name("nombre")).sendKeys("i1");
    driver.findElement(By.name("apellido_1")).sendKeys("i1");
    driver.findElement(By.name("apellido_2")).sendKeys("i1");
    driver.findElement(By.name("email")).sendKeys("i1");
    driver.findElement(By.name("usuario")).sendKeys("i1");
    driver.findElement(By.name("password")).sendKeys("i1");
    driver.findElement(By.cssSelector(".text-center > button")).click();
    driver.findElement(By.name("cif")).click();
    driver.findElement(By.name("cif")).sendKeys("e1");
    driver.findElement(By.cssSelector("#margen > #admin > #margen .col:nth-child(2) > input")).sendKeys("e1");
    driver.findElement(By.name("direccion")).sendKeys("e1");
    driver.findElement(By.name("ciudad")).sendKeys("e1");
    driver.findElement(By.name("codigo_postal")).sendKeys("e1");
    driver.findElement(By.name("rep_legal")).sendKeys("e1");
    driver.findElement(By.name("tipo")).click();
    {
      WebElement dropdown = driver.findElement(By.name("tipo"));
      dropdown.findElement(By.xpath("//option[. = 'Restaurante']")).click();
    }
    driver.findElement(By.name("tipo")).click();
    driver.findElement(By.cssSelector(".col:nth-child(4) > button")).click();
    driver.findElement(By.name("nombre")).click();
    driver.findElement(By.name("nombre")).sendKeys("i1");
    driver.findElement(By.name("apellido_1")).sendKeys("i1");
    driver.findElement(By.name("apellido_2")).sendKeys("i1");
    driver.findElement(By.name("email")).sendKeys("i1");
    driver.findElement(By.name("usuario")).sendKeys("i1");
    driver.findElement(By.name("password")).sendKeys("i1");
    driver.findElement(By.cssSelector(".text-center > button")).click();
    driver.findElement(By.name("cif")).click();
    driver.findElement(By.name("cif")).sendKeys("e1");
    driver.findElement(By.cssSelector("#margen > #admin > #margen .col:nth-child(2) > input")).sendKeys("e2");
    driver.findElement(By.name("direccion")).sendKeys("e2");
    driver.findElement(By.name("ciudad")).sendKeys("e2");
    driver.findElement(By.name("codigo_postal")).sendKeys("e2");
    driver.findElement(By.name("rep_legal")).sendKeys("e2");
    driver.findElement(By.name("tipo")).click();
    {
      WebElement dropdown = driver.findElement(By.name("tipo"));
      dropdown.findElement(By.xpath("//option[. = 'Bar']")).click();
    }
    driver.findElement(By.name("tipo")).click();
    driver.findElement(By.cssSelector(".col:nth-child(4) > button")).click();
    driver.findElement(By.cssSelector(".btn")).click();
  }
}
